# Generated by Django 4.2.6 on 2023-10-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email cannot be blank.', 'unique': 'This email is already registered.'}, max_length=254, unique=True),
        ),
    ]
